import type { NextPage } from "next";
import Head from "next/head";
import BioCard from "../../components/BioCard";
import styles from "../../styles/screens/About.module.css";
import Education from "./(subscreens)/education";
import Skills from "./(subscreens)/skills";

const Home: NextPage = () => {
  return (
    <main className={styles.container}>
      <Head>
        <title>Sean Loveland</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="profile.jpg" />
      </Head>
      <BioCard />
      <Skills />
      <Education />
    </main>
  );
};

export default Home;
