import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BioCard from '../components/BioCard'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sean Loveland</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BioCard />
        
    </div>
  )
}

export default Home
